# Generated by Django 4.0.5 on 2022-06-16 03:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
                ('closed_auction', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('parroquia', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=200)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('propietario', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('redes_sociales', models.CharField(max_length=100)),
                ('asociacion', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('equipos', models.CharField(max_length=500)),
                ('equipos_cocina', models.CharField(max_length=500)),
                ('servicios_complementarios', models.CharField(max_length=500)),
                ('numero_mesas', models.IntegerField()),
                ('plazas', models.IntegerField()),
                ('banio', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('oferta', models.CharField(max_length=200)),
                ('tipo_servicio', models.CharField(max_length=200)),
                ('menu', models.TextField(max_length=1200, null=True)),
                ('precio_promedio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proceso', models.CharField(max_length=200)),
                ('materias_primas', models.CharField(max_length=200)),
                ('tipo_materia_prima', models.CharField(max_length=200)),
                ('numero_mujeres', models.IntegerField()),
                ('numero_hombres', models.IntegerField()),
                ('formacion_academica', models.CharField(max_length=200)),
                ('personal_capacitado', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('frecuencia_capacitacion', models.CharField(max_length=200)),
                ('empleados_formacion', models.CharField(max_length=200)),
                ('licencia_anual', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('url', models.URLField(blank=True, max_length=250, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
