# Generated by Django 4.0.5 on 2022-06-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronomia', '0002_rename_closed_auction_establecimiento_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
