# Generated by Django 4.0.5 on 2022-08-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronomia', '0003_alter_establecimiento_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='equipos',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='equipos_cocina',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='materias_primas',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='nombre',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='oferta',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='proceso',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='servicios_complementarios',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='tipo_materia_prima',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='tipo_servicio',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
