# Generated by Django 4.0.5 on 2022-08-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronomia', '0004_alter_establecimiento_equipos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='banio',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='licencia_anual',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=20),
        ),
    ]
